kind: Pod
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: name
        value: "Vijaya L Koduri"
      - name: Profession
        value: "Devops Engineer"      
      - name: Experience
        value: "3 years"